name: CI Workflow

on:
  push:
    branches: []
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest    

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.0
      uses: actions/setup-node@v3
      with:
        node-version: 18.0
        cache: 'npm'
    - name: Install node modules    
      run: npm install
    - name: Start the app    
      run: npm start
    - name: Run the tests  
      run: npm test